version: '2.1'
services:
  dbmate:
    build: .
    volumes:
      - .:/go/src/github.com/turnitin/dbmate
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "status", "-proot"]

  postgres:
    image: postgres:alpine
    healthcheck:
      test: ["CMD", "pg_isready"]
